<?php

namespace Database\Seeders;

use Carbon\Carbon;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class StudentSeeder extends Seeder
{
    public function run()
    {
        $students = [
            ['full_name' => 'ABDULLAH KHUBAIB ASYUJA', 'nis' => 'A-509', 'nisn' => '3122396810', 'gender' => 'Laki-laki', 'address' => 'KAB. SEMARANG', 'phone_number' => null],
            ['full_name' => 'AFHAM SHOLIHAH', 'nis' => 'A-510', 'nisn' => '3125322155', 'gender' => 'Perempuan', 'address' => 'SUKOHARJO', 'phone_number' => null],
            ['full_name' => 'AFIYAH KHOFFATUN NAJAH', 'nis' => 'A-511', 'nisn' => '3129133423', 'gender' => 'Perempuan', 'address' => 'Surakarta', 'phone_number' => null],
            ['full_name' => 'AIR NAKHLA ABYAN', 'nis' => 'A-512', 'nisn' => '3128324031', 'gender' => 'Laki-laki', 'address' => 'SUKOHARJO', 'phone_number' => null],
            ['full_name' => 'AKHSAN MAHDHIYAH LAILA ALI', 'nis' => 'A-513', 'nisn' => '0127059999', 'gender' => 'Perempuan', 'address' => 'SURAKARTA', 'phone_number' => null],
            ['full_name' => 'AMIRUL AZFA', 'nis' => 'A-514', 'nisn' => '3111778993', 'gender' => 'Laki-laki', 'address' => 'SURAKARTA', 'phone_number' => null],
            ['full_name' => 'AQILLA AZ ZAHRA', 'nis' => 'A-515', 'nisn' => '3128583539', 'gender' => 'Perempuan', 'address' => 'Sukoharjo', 'phone_number' => null],
            ['full_name' => 'ARIDNA HAFISA FATAN', 'nis' => 'A-516', 'nisn' => '3132168809', 'gender' => 'Perempuan', 'address' => 'Sukoharjo', 'phone_number' => null],
            ['full_name' => 'ASMA\'', 'nis' => 'A-517', 'nisn' => '3121440379', 'gender' => 'Perempuan', 'address' => 'Sukoharjo', 'phone_number' => null],
            ['full_name' => 'DEVDHAN KHALIM', 'nis' => 'A-518', 'nisn' => '3135305364', 'gender' => 'Laki-laki', 'address' => 'BEKASI', 'phone_number' => null],
            ['full_name' => 'ELQI JAYA AKHMAD', 'nis' => 'A-519', 'nisn' => '3132401259', 'gender' => 'Laki-laki', 'address' => 'SURAKARTA', 'phone_number' => null],
            ['full_name' => 'FADHILDDIN', 'nis' => 'A-520', 'nisn' => '3129175575', 'gender' => 'Laki-laki', 'address' => 'SUKOHARJO', 'phone_number' => null],
            ['full_name' => 'FARKHAT AZ ZAHIN', 'nis' => 'A-521', 'nisn' => '3127731384', 'gender' => 'Laki-laki', 'address' => 'Sukoharjo', 'phone_number' => null],
            ['full_name' => 'FAROH AULIYAH SYAHIDAH', 'nis' => 'A-522', 'nisn' => '3130112328', 'gender' => 'Perempuan', 'address' => 'SURAKARTA', 'phone_number' => null],
            ['full_name' => 'FAZA MIFZAL MAIA2', 'nis' => 'A-523', 'nisn' => '3129477096', 'gender' => 'Laki-laki', 'address' => 'BLORA', 'phone_number' => null],
            ['full_name' => 'FIDYA AYUNING TIAHA RAMADANI', 'nis' => 'A-524', 'nisn' => '3138778352', 'gender' => 'Perempuan', 'address' => 'SEMARANG', 'phone_number' => null],
            ['full_name' => 'FILZA TSABITA AL HASNA', 'nis' => 'A-525', 'nisn' => '3138246734', 'gender' => 'Perempuan', 'address' => 'Sukoharjo', 'phone_number' => null],
            ['full_name' => 'GHAZIYA HAFIZHA KHAIRUNNISA', 'nis' => 'A-526', 'nisn' => '3123576145', 'gender' => 'Perempuan', 'address' => 'Surakarta', 'phone_number' => null],
            ['full_name' => 'GHIBON MAFATIHURRIZQI', 'nis' => 'A-527', 'nisn' => '3116164650', 'gender' => 'Laki-laki', 'address' => 'SUMEDANG', 'phone_number' => null],
            ['full_name' => 'HAMMAM MUTASHIM', 'nis' => 'A-528', 'nisn' => '3130022022', 'gender' => 'Laki-laki', 'address' => 'SUKOHARJO', 'phone_number' => null],
            ['full_name' => 'HEIDYA EMANIE FAUZIE', 'nis' => 'A-529', 'nisn' => '3137890241', 'gender' => 'Perempuan', 'address' => 'Surakarta', 'phone_number' => null],
            ['full_name' => 'ISMAIL ALI FARUQI', 'nis' => 'A-530', 'nisn' => '3147982998', 'gender' => 'Laki-laki', 'address' => 'SUKOHARJO', 'phone_number' => null],
            ['full_name' => 'IYAS NUR MUA\'AFA', 'nis' => 'A-531', 'nisn' => '3121096985', 'gender' => 'Laki-laki', 'address' => 'SUKOHARJO', 'phone_number' => null],
            ['full_name' => 'JANEETA IQLIMA HAMZAH', 'nis' => 'A-532', 'nisn' => '3127019057', 'gender' => 'Perempuan', 'address' => 'SURAKARTA', 'phone_number' => null],
            ['full_name' => 'JIHAN KIYOSI AR-RAYAN', 'nis' => 'A-533', 'nisn' => '3135455528', 'gender' => 'Perempuan', 'address' => 'Surakarta', 'phone_number' => null],
            ['full_name' => 'KARIMA SULTHANA', 'nis' => 'A-534', 'nisn' => '3124207582', 'gender' => 'Perempuan', 'address' => 'SURAKARTA', 'phone_number' => null],
            ['full_name' => 'KHANSA AS SAYIDAH', 'nis' => 'A-535', 'nisn' => '3129879243', 'gender' => 'Perempuan', 'address' => 'KARANGANYAR', 'phone_number' => null],
            ['full_name' => 'KHAULAH NUSAIBAH AZ ZAHRA', 'nis' => 'A-536', 'nisn' => '3120704462', 'gender' => 'Perempuan', 'address' => 'Sukoharjo', 'phone_number' => null],
            ['full_name' => 'LAILA IZZA SYAHIDAH', 'nis' => 'A-537', 'nisn' => '3121504437', 'gender' => 'Perempuan', 'address' => 'SURAKARTA', 'phone_number' => null],
            ['full_name' => 'LATIFAH DINI ALMUNAWA\'ARAH', 'nis' => 'A-538', 'nisn' => '3130266284', 'gender' => 'Perempuan', 'address' => 'SURAKARTA', 'phone_number' => null],
            ['full_name' => 'LUQMAN HANAFI', 'nis' => 'A-539', 'nisn' => '3129842696', 'gender' => 'Laki-laki', 'address' => 'SURAKARTA', 'phone_number' => null],
            ['full_name' => 'LUTHFIA MUFIDAH KHOIRUNNISA', 'nis' => 'A-540', 'nisn' => '3125201280', 'gender' => 'Perempuan', 'address' => 'SURAKARTA', 'phone_number' => null],
            ['full_name' => 'MUAZAH', 'nis' => 'A-541', 'nisn' => '3130264538', 'gender' => 'Perempuan', 'address' => 'SUKOHARJO', 'phone_number' => null],
            ['full_name' => 'MUHAMMAD FAISAL BURDAN', 'nis' => 'A-542', 'nisn' => '3126201791', 'gender' => 'Laki-laki', 'address' => 'KARANGANYAR', 'phone_number' => null],
            ['full_name' => 'MUHAMMAD IMAM FADILLAH', 'nis' => 'A-543', 'nisn' => '0136549543', 'gender' => 'Laki-laki', 'address' => 'BLORA', 'phone_number' => null],
            ['full_name' => 'MUHAMMAD MUTTAQI MAFAZA', 'nis' => 'A-544', 'nisn' => '3113805436', 'gender' => 'Laki-laki', 'address' => 'NGAWI', 'phone_number' => null],
            ['full_name' => 'MUHAMMAD SHAQUILLE ZIMAM AFSHAH', 'nis' => 'A-545', 'nisn' => '0121159462', 'gender' => 'Laki-laki', 'address' => 'BLITAR', 'phone_number' => null],
            ['full_name' => 'MUHAMMAD SHOLHIN', 'nis' => 'A-546', 'nisn' => '3136670023', 'gender' => 'Laki-laki', 'address' => 'KARANGANYAR', 'phone_number' => null],
            ['full_name' => 'NADYA GHEFIRA AS SYAHIDAH', 'nis' => 'A-547', 'nisn' => '3130424095', 'gender' => 'Perempuan', 'address' => 'Sukoharjo', 'phone_number' => null],
            ['full_name' => 'NAILA IZZA SYAHIDAH', 'nis' => 'A-548', 'nisn' => '3128513617', 'gender' => 'Perempuan', 'address' => 'SURAKARTA', 'phone_number' => null],
            ['full_name' => 'NUSAIBAH SYAUQI SYAHIDAH', 'nis' => 'A-549', 'nisn' => '3127268686', 'gender' => 'Perempuan', 'address' => 'KAB. SEMARANG', 'phone_number' => null],
            ['full_name' => 'RAMADHAN NUR WIRABUANA', 'nis' => 'A-550', 'nisn' => '3120325481', 'gender' => 'Laki-laki', 'address' => 'SURAKARTA', 'phone_number' => null],
            ['full_name' => 'ROBBANIYYAH DCKAYYAH', 'nis' => 'A-551', 'nisn' => '3134526024', 'gender' => 'Perempuan', 'address' => 'SURAKARTA', 'phone_number' => null],
            ['full_name' => 'RUMAISHA AL ANSHARIAH', 'nis' => 'A-552', 'nisn' => '3137774790', 'gender' => 'Perempuan', 'address' => 'KARANGANYAR', 'phone_number' => null],
            ['full_name' => 'SABRINA AULIA RAHMAH', 'nis' => 'A-553', 'nisn' => '3132154216', 'gender' => 'Perempuan', 'address' => 'Karanganyar', 'phone_number' => null],
            ['full_name' => 'SAFFANAH AL QISHT', 'nis' => 'A-554', 'nisn' => '3122249221', 'gender' => 'Perempuan', 'address' => 'LEBAK', 'phone_number' => null],
            ['full_name' => 'SAKIEB RAMADHANI WINARNO', 'nis' => 'A-555', 'nisn' => '3134579687', 'gender' => 'Perempuan', 'address' => 'SUKOHARJO', 'phone_number' => null],
            ['full_name' => 'SHASMIRA BILQIS QURROTA A\'YUN ALMUKMIN', 'nis' => 'A-556', 'nisn' => '3115085674', 'gender' => 'Perempuan', 'address' => 'Surakarta', 'phone_number' => null],
            ['full_name' => 'SYAKIRA NU\'MA EL QAIDA', 'nis' => 'A-557', 'nisn' => '0128902439', 'gender' => 'Perempuan', 'address' => 'Surakarta', 'phone_number' => null],
            ['full_name' => 'SYIFAUL AQRA KAMILA', 'nis' => 'A-558', 'nisn' => '3122260774', 'gender' => 'Perempuan', 'address' => 'PURWOREJO', 'phone_number' => null],
            ['full_name' => 'TAQIYA CHOIRUNNISA', 'nis' => 'A-559', 'nisn' => '3131471738', 'gender' => 'Perempuan', 'address' => 'SUKOHARJO', 'phone_number' => null],
            ['full_name' => 'UMMU MUTIAH', 'nis' => 'A-560', 'nisn' => '3123512297', 'gender' => 'Perempuan', 'address' => 'SUKOHARJO', 'phone_number' => null],
            ['full_name' => 'USMAN ABDURRAHMAN', 'nis' => 'A-561', 'nisn' => '3122784460', 'gender' => 'Laki-laki', 'address' => 'SURAKARTA', 'phone_number' => null],
            ['full_name' => 'WILDAN FADHIL MUKHLISHIN SULAIMAN', 'nis' => 'A-562', 'nisn' => '3130570398', 'gender' => 'Laki-laki', 'address' => 'SUKOHARJO', 'phone_number' => null],
            ['full_name' => 'ZAHRA ALMAIRA AZIZAH RAHMAN', 'nis' => 'A-563', 'nisn' => '3132585365', 'gender' => 'Perempuan', 'address' => 'SURAKARTA', 'phone_number' => null],
            ['full_name' => 'ZULFA FAUZIYAH', 'nis' => 'A-564', 'nisn' => '3137688172', 'gender' => 'Perempuan', 'address' => 'SURAKARTA', 'phone_number' => null],
            ['full_name' => 'A\'ISYAH HUMAIRA MUHAMMAD', 'nis' => 'A-565', 'nisn' => '3131979993', 'gender' => 'Perempuan', 'address' => 'SURAKARTA', 'phone_number' => null],
            ['full_name' => '\'AISYAH AL-HUMAIRO', 'nis' => 'A-566', 'nisn' => '3130823091', 'gender' => 'Perempuan', 'address' => 'Sukoharjo', 'phone_number' => null],
            ['full_name' => 'ABDURROHMAN USAMAH ACHMAD AL-FALIH', 'nis' => 'A-567', 'nisn' => '0158626937', 'gender' => 'Laki-laki', 'address' => 'Sukoharjo', 'phone_number' => null],
            ['full_name' => 'ADZKIA NAUROH ABDILLAH', 'nis' => 'A-568', 'nisn' => '3137255299', 'gender' => 'Laki-laki', 'address' => 'Surakarta', 'phone_number' => null],
            ['full_name' => 'AHMAD YASSIN', 'nis' => 'A-569', 'nisn' => '3138565947', 'gender' => 'Laki-laki', 'address' => 'Surakarta', 'phone_number' => null],
            ['full_name' => 'AQILA SILMI NAFISAH', 'nis' => 'A-570', 'nisn' => '3123536238', 'gender' => 'Perempuan', 'address' => 'Sukoharjo', 'phone_number' => null],
            ['full_name' => 'AZKA PUTRA MAHENDRA', 'nis' => 'A-574', 'nisn' => '3133851219', 'gender' => 'Laki-laki', 'address' => 'Sukoharjo', 'phone_number' => null],
            ['full_name' => 'MUHAMMAD DANISWARA ATHAYA', 'nis' => 'A-575', 'nisn' => '3133287990', 'gender' => 'Laki-laki', 'address' => 'Surakarta', 'phone_number' => null],
            ['full_name' => 'Muhammad Haidar Saifullah', 'nis' => 'A-576', 'nisn' => '3122694790', 'gender' => 'Laki-laki', 'address' => 'Sukoharjo', 'phone_number' => null],
            ['full_name' => 'MUHAMMAD UMAR IBNU MUJAHID', 'nis' => 'A-577', 'nisn' => '3137995672', 'gender' => 'Laki-laki', 'address' => 'Surakarta', 'phone_number' => null],
            ['full_name' => 'MUSAB ALI SHOZY', 'nis' => 'A-578', 'nisn' => '3127585214', 'gender' => 'Laki-laki', 'address' => 'Sukoharjo', 'phone_number' => null],

            // PAKET B - Program ID: 2
            ['full_name' => 'Abdul Hakim Kaisa Ahya Ulmari', 'nis' => 'B-236', 'nisn' => '0096438781', 'gender' => 'Laki-laki', 'address' => 'Karanganyar', 'phone_number' => null],
            ['full_name' => 'ABDULLOH UMAR faruqi', 'nis' => 'B-237', 'nisn' => '3101958647', 'gender' => 'Laki-laki', 'address' => 'Sukoharjo', 'phone_number' => null],
            ['full_name' => 'ABDURRAHMAN FAUZY', 'nis' => 'B-238', 'nisn' => '3041574262', 'gender' => 'Laki-laki', 'address' => 'PALANGKA RAYA', 'phone_number' => null],
            ['full_name' => 'AHMAD DIENO MUSTANIRO', 'nis' => 'B-239', 'nisn' => '2097523557', 'gender' => 'Laki-laki', 'address' => 'BEKASI', 'phone_number' => null],
            ['full_name' => 'ALVINO FAJAR DISTIAWAN', 'nis' => 'B-240', 'nisn' => '0104472147', 'gender' => 'Laki-laki', 'address' => 'SURAKARTA', 'phone_number' => null],
            ['full_name' => 'AMAR MA\'RUF NASRULLAH', 'nis' => 'B-241', 'nisn' => '2107127649', 'gender' => 'Laki-laki', 'address' => 'BAGAN BATU', 'phone_number' => null],
            ['full_name' => 'ANDY ANGRIANTO JAYA', 'nis' => 'B-242', 'nisn' => '0056655421', 'gender' => 'Laki-laki', 'address' => 'SOLO', 'phone_number' => null],
            ['full_name' => 'ARIFA YUMMAHIMILIA', 'nis' => 'B-243', 'nisn' => '3091445342', 'gender' => 'Laki-laki', 'address' => 'JAKARTA', 'phone_number' => null],
            ['full_name' => 'ASNA SYAMIL', 'nis' => 'B-244', 'nisn' => '0073002960', 'gender' => 'Perempuan', 'address' => 'SUKOHARJO', 'phone_number' => null],
            ['full_name' => 'ATHLIFA ZULFITRA FAUZIAH', 'nis' => 'B-245', 'nisn' => '0151207851', 'gender' => 'Perempuan', 'address' => 'SURAKARTA', 'phone_number' => null],
            ['full_name' => 'AULIA RAHMAH', 'nis' => 'B-246', 'nisn' => '3108379664', 'gender' => 'Perempuan', 'address' => 'SUKOHARJO', 'phone_number' => null],
            ['full_name' => 'CHOIRUL BANU FITROHA', 'nis' => 'B-247', 'nisn' => '0097774514', 'gender' => 'Laki-laki', 'address' => 'Boyolali', 'phone_number' => null],
            ['full_name' => 'CITRA SARI DEWI', 'nis' => 'B-248', 'nisn' => '3100169491', 'gender' => 'Perempuan', 'address' => 'surakarta', 'phone_number' => null],
            ['full_name' => 'HAMZAH', 'nis' => 'B-249', 'nisn' => '2104929075', 'gender' => 'Laki-laki', 'address' => 'SUKOHARJO', 'phone_number' => null],
            ['full_name' => 'HELENA YOGIE WIDYASMORO', 'nis' => 'B-250', 'nisn' => '0093538797', 'gender' => 'Perempuan', 'address' => 'SURAKARTA', 'phone_number' => null],
            ['full_name' => 'HULINNI NUM MAFAZA Fathika', 'nis' => 'B-251', 'nisn' => '3106348878', 'gender' => 'Perempuan', 'address' => 'surakarta', 'phone_number' => null],
            ['full_name' => 'IRNANDA RIZQI OKTAVIAN', 'nis' => 'B-252', 'nisn' => '0020266618', 'gender' => 'Laki-laki', 'address' => 'SURAKARTA', 'phone_number' => null],
            ['full_name' => 'JIHAN AULIA SYAHIDAH', 'nis' => 'B-253', 'nisn' => '3103843522', 'gender' => 'Perempuan', 'address' => 'SURAKARTA', 'phone_number' => null],
            ['full_name' => 'KAYLA ARUM NUR HIKMAH', 'nis' => 'B-254', 'nisn' => '0098554681', 'gender' => 'Perempuan', 'address' => 'BREBES', 'phone_number' => null],
            ['full_name' => 'KHATIDIAH FAERUS SABA', 'nis' => 'B-255', 'nisn' => '2107215118', 'gender' => 'Perempuan', 'address' => 'SUKOHARJO', 'phone_number' => null],
            ['full_name' => 'M. Fathul Mafaza Damanis', 'nis' => 'B-256', 'nisn' => '0088784613', 'gender' => 'Laki-laki', 'address' => 'Brebes', 'phone_number' => null],
            ['full_name' => 'MUHAMMAD ILHAM fattah', 'nis' => 'B-257', 'nisn' => '3108734475', 'gender' => 'Laki-laki', 'address' => 'wonogiri', 'phone_number' => null],
            ['full_name' => 'MUHAMMAD ROFI\' NASHRULLOH', 'nis' => 'B-258', 'nisn' => '2102215126', 'gender' => 'Laki-laki', 'address' => 'SRAGEN', 'phone_number' => null],
            ['full_name' => 'MUHAMMAD SALMAN ALFARUQ', 'nis' => 'B-259', 'nisn' => '2087351975', 'gender' => 'Laki-laki', 'address' => 'SURAKARTA', 'phone_number' => null],
            ['full_name' => 'MUHAMMAD UMAR AZZAM', 'nis' => 'B-260', 'nisn' => '2099106129', 'gender' => 'Laki-laki', 'address' => 'LEBAK', 'phone_number' => null],
            ['full_name' => 'QOID MUHAMMAD SAYYAF', 'nis' => 'B-261', 'nisn' => '2104212163', 'gender' => 'Laki-laki', 'address' => 'JOGJA', 'phone_number' => null],
            ['full_name' => 'NUR HIKMATUL OKTAFIANI', 'nis' => 'B-262', 'nisn' => '0099299304', 'gender' => 'Perempuan', 'address' => 'BREBES', 'phone_number' => null],
            ['full_name' => 'SHOFIYATUL \'AINI', 'nis' => 'B-263', 'nisn' => '2105166893', 'gender' => 'Perempuan', 'address' => 'SURAKARTA', 'phone_number' => null],
            ['full_name' => 'SHOFIYYAH NABA AZ-ZAHRA', 'nis' => 'B-264', 'nisn' => '2079326958', 'gender' => 'Perempuan', 'address' => 'SURAKARTA', 'phone_number' => null],
            ['full_name' => 'SUPRIANTO', 'nis' => 'B-265', 'nisn' => '3732675849', 'gender' => 'Laki-laki', 'address' => 'BLORA', 'phone_number' => null],
            ['full_name' => 'UMAR AL FAKHRI', 'nis' => 'B-266', 'nisn' => '0107124391', 'gender' => 'Laki-laki', 'address' => 'Pemalang', 'phone_number' => null],
            ['full_name' => 'UNGGUL FIRAAS ALGHIFARI', 'nis' => 'B-267', 'nisn' => '0093810775', 'gender' => 'Laki-laki', 'address' => 'CILACAP', 'phone_number' => null],
            ['full_name' => 'Rafifuddin Ahmad Fauzi', 'nis' => 'B-268', 'nisn' => '0096349040', 'gender' => 'Laki-laki', 'address' => 'Surakarta', 'phone_number' => null],
            ['full_name' => 'DEVANKA NUR RACHIMA', 'nis' => 'B-269', 'nisn' => '0056191802', 'gender' => 'Laki-laki', 'address' => 'CILACAP', 'phone_number' => null],
            ['full_name' => 'Ibrahim Ihsanul Anam', 'nis' => 'B-270', 'nisn' => '3091596836', 'gender' => 'Laki-laki', 'address' => 'Batam', 'phone_number' => null],
            ['full_name' => 'M. FAHIM MUBARRAK', 'nis' => 'B-271', 'nisn' => '0093189874', 'gender' => 'Laki-laki', 'address' => 'BATAM', 'phone_number' => null],
            ['full_name' => 'JUNDI MASHBORUDDIEN', 'nis' => 'B-272', 'nisn' => '3090043398', 'gender' => 'Laki-laki', 'address' => 'BATAM', 'phone_number' => null],
            ['full_name' => 'DHIYA \'UDDIN AL FATIH', 'nis' => 'B-273', 'nisn' => '3088921550', 'gender' => 'Laki-laki', 'address' => 'BATAM', 'phone_number' => null],
            ['full_name' => 'AHMAD HAMDAN SYAKUR', 'nis' => 'B-274', 'nisn' => '0091726754', 'gender' => 'Laki-laki', 'address' => 'BATAM', 'phone_number' => null],
            ['full_name' => 'SOFI AULIA RAMADHANI', 'nis' => 'B-276', 'nisn' => '0091801308', 'gender' => 'Perempuan', 'address' => 'Ngawi', 'phone_number' => null],

            // PAKET C - IPA - Program ID: 3
            ['full_name' => 'AKBAR IKSAN WIJAYA', 'nis' => 'C-462', 'nisn' => '0019879069', 'gender' => 'Laki-laki', 'address' => 'BANJAR AGUNG', 'phone_number' => null],
            ['full_name' => 'DAVID ALEXANDER HARYONO', 'nis' => 'C-463', 'nisn' => '0055995544', 'gender' => 'Laki-laki', 'address' => 'SRAGEN', 'phone_number' => null],
            ['full_name' => 'HAKIM AKBAR KAMAJAYA', 'nis' => 'C-464', 'nisn' => '3062905201', 'gender' => 'Laki-laki', 'address' => 'KARANGANYAR', 'phone_number' => null],
            ['full_name' => 'HALIM HIDAYAT', 'nis' => 'C-465', 'nisn' => '3072251640', 'gender' => 'Laki-laki', 'address' => 'NGANJUK', 'phone_number' => null],
            ['full_name' => 'Hermitasari', 'nis' => 'C-466', 'nisn' => '0011147763', 'gender' => 'Perempuan', 'address' => 'Wonogiri', 'phone_number' => null],
            ['full_name' => 'Husna El Saliha', 'nis' => 'C-467', 'nisn' => '0061428499', 'gender' => 'Perempuan', 'address' => 'Surakarta', 'phone_number' => null],
            ['full_name' => 'MANSHUR ABIDIN', 'nis' => 'C-468', 'nisn' => '0073866826', 'gender' => 'Laki-laki', 'address' => 'SUKOHARJO', 'phone_number' => null],
            ['full_name' => 'Mohamad Juliansyah Chen', 'nis' => 'C-469', 'nisn' => '3073906878', 'gender' => 'Laki-laki', 'address' => 'Batam', 'phone_number' => null],
            ['full_name' => 'MOHAMMAD ZIDANE NURROIHAN', 'nis' => 'C-470', 'nisn' => '0065591370', 'gender' => 'Laki-laki', 'address' => 'PURBALINGGA', 'phone_number' => null],
            ['full_name' => 'Much Yunus Ismail', 'nis' => 'C-471', 'nisn' => '0056650821', 'gender' => 'Laki-laki', 'address' => 'Sukoharjo', 'phone_number' => null],
            ['full_name' => 'MUHAMAD NAUFAL AMMAR', 'nis' => 'C-472', 'nisn' => '0058527603', 'gender' => 'Laki-laki', 'address' => 'SURAKARTA', 'phone_number' => null],
            ['full_name' => 'MUHAMMAD ALFATIH', 'nis' => 'C-473', 'nisn' => '3075204968', 'gender' => 'Laki-laki', 'address' => 'Banyumas', 'phone_number' => null],
            ['full_name' => 'MUHAMMAD DWI PUTRA RIZKIA AL BARA', 'nis' => 'C-474', 'nisn' => '0055369145', 'gender' => 'Laki-laki', 'address' => 'PURWAKARTA', 'phone_number' => null],
            ['full_name' => 'MUHAMMAD FATHI FARHAT', 'nis' => 'C-475', 'nisn' => '0058008688', 'gender' => 'Laki-laki', 'address' => 'BEKASI', 'phone_number' => null],
            ['full_name' => 'MUHAMMAD YUSUF IHSAN PRADANA', 'nis' => 'C-476', 'nisn' => '0089539437', 'gender' => 'Laki-laki', 'address' => 'SURAKARTA', 'phone_number' => null],
            ['full_name' => 'NAYLA MUNAYA', 'nis' => 'C-477', 'nisn' => '0075001614', 'gender' => 'Perempuan', 'address' => 'SUKOHARJO', 'phone_number' => null],
            ['full_name' => 'RUMAISHA LAILA EL FADHILAH', 'nis' => 'C-478', 'nisn' => '0066708952', 'gender' => 'Perempuan', 'address' => 'MAGELANG', 'phone_number' => null],
            ['full_name' => 'Sekar Ayu Kinanti', 'nis' => 'C-479', 'nisn' => '9993860193', 'gender' => 'Perempuan', 'address' => 'Surakarta', 'phone_number' => null],
            ['full_name' => 'SUCIA EKK\'Y RAMANDANI', 'nis' => 'C-480', 'nisn' => '3099853999', 'gender' => 'Perempuan', 'address' => 'SURAKARTA', 'phone_number' => null],
            ['full_name' => 'Wahyu Nugroho', 'nis' => 'C-481', 'nisn' => '0049973345', 'gender' => 'Laki-laki', 'address' => 'Sukoharjo', 'phone_number' => null],
            ['full_name' => 'ZAHRA NURJANNAH mahmudah', 'nis' => 'C-482', 'nisn' => '3068263832', 'gender' => 'Perempuan', 'address' => 'sukoharjo', 'phone_number' => null],
            ['full_name' => 'ZASQA SHAFFAARIFIN', 'nis' => 'C-483', 'nisn' => '0076146399', 'gender' => 'Perempuan', 'address' => 'GARUT', 'phone_number' => null],
            ['full_name' => 'ZILDAN ILYASA YUSFIANDIZAKY', 'nis' => 'C-484', 'nisn' => '0068051054', 'gender' => 'Laki-laki', 'address' => 'Wonogiri', 'phone_number' => null],
            ['full_name' => 'ABDULLAH', 'nis' => 'C-485', 'nisn' => '3065900946', 'gender' => 'Laki-laki', 'address' => 'Pemalang', 'phone_number' => null],
            ['full_name' => 'ABDULLAH SUFYAN AL HAFIDZ', 'nis' => 'C-486', 'nisn' => '3047394332', 'gender' => 'Laki-laki', 'address' => 'Surakarta', 'phone_number' => null],
            ['full_name' => 'ASHIM ABDUL AZIS', 'nis' => 'C-487', 'nisn' => '0038935172', 'gender' => 'Laki-laki', 'address' => 'Sukoharjo', 'phone_number' => null],
            ['full_name' => 'FATHAN NAUFAL ASYRAF', 'nis' => 'C-488', 'nisn' => '0067437175', 'gender' => 'Laki-laki', 'address' => 'SURAKARTA', 'phone_number' => null],
            ['full_name' => 'FATIH ZADA WIBOWO', 'nis' => 'C-489', 'nisn' => '0079990599', 'gender' => 'Laki-laki', 'address' => 'Surakarta', 'phone_number' => null],
            ['full_name' => 'HAIDAR ZAKKI', 'nis' => 'C-490', 'nisn' => '0064377286', 'gender' => 'Laki-laki', 'address' => 'Surakarta', 'phone_number' => null],
            ['full_name' => 'IYADH RIZQUNA', 'nis' => 'C-491', 'nisn' => '0059058096', 'gender' => 'Laki-laki', 'address' => 'Karanganyar', 'phone_number' => null],
            ['full_name' => 'MUFID ABDURROHIM', 'nis' => 'C-492', 'nisn' => '0072870497', 'gender' => 'Laki-laki', 'address' => 'Kendal', 'phone_number' => null],
            ['full_name' => 'MUHADZIDZIB ABIB ABIYYU', 'nis' => 'C-493', 'nisn' => '0132399571', 'gender' => 'Laki-laki', 'address' => 'Sragen', 'phone_number' => null],
            ['full_name' => 'MUHAMMAD ALFAKHRI', 'nis' => 'C-494', 'nisn' => '0075172924', 'gender' => 'Laki-laki', 'address' => 'Surakarta', 'phone_number' => null],
            ['full_name' => 'MUHAMMAD FATIH ADZKIYA NUR HIDAYA', 'nis' => 'C-495', 'nisn' => '0069157247', 'gender' => 'Laki-laki', 'address' => 'Boyolali', 'phone_number' => null],
            ['full_name' => 'MUHAMMAD RAFIQ', 'nis' => 'C-496', 'nisn' => '0061803236', 'gender' => 'Laki-laki', 'address' => 'Wonogiri', 'phone_number' => null],
            ['full_name' => 'MUHAMMAD RAZZAN AL FARUQ', 'nis' => 'C-497', 'nisn' => '0071532560', 'gender' => 'Laki-laki', 'address' => 'Kediri', 'phone_number' => null],
            ['full_name' => 'MUHAMMAD RIZIQ ALI MUSYAFA', 'nis' => 'C-498', 'nisn' => '0075510818', 'gender' => 'Laki-laki', 'address' => 'Surakarta', 'phone_number' => null],
            ['full_name' => 'RAIHAN NARENDRA PUTRA', 'nis' => 'C-499', 'nisn' => '0077569651', 'gender' => 'Laki-laki', 'address' => 'Sukoharjo', 'phone_number' => null],
            ['full_name' => 'SAIFULLAH ALBATTAR', 'nis' => 'C-500', 'nisn' => '3060796922', 'gender' => 'Laki-laki', 'address' => 'Surakarta', 'phone_number' => null],
            ['full_name' => 'ZIAUL HAQ AHMAD ROSYADI', 'nis' => 'C-501', 'nisn' => '0054801084', 'gender' => 'Laki-laki', 'address' => 'SURAKARTA', 'phone_number' => null],

            // PAKET C - IPS - Program ID: 3
            ['full_name' => 'ACHUN AUFA', 'nis' => 'C-412', 'nisn' => '0025494154', 'gender' => 'Laki-laki', 'address' => 'WONOSOBO', 'phone_number' => null],
            ['full_name' => 'AGUS SUTAMTO', 'nis' => 'C-413', 'nisn' => '3838440428', 'gender' => 'Laki-laki', 'address' => 'SRAGEN', 'phone_number' => null],
            ['full_name' => 'Ahmad Roihan Zaeni', 'nis' => 'C-414', 'nisn' => '0030124850', 'gender' => 'Laki-laki', 'address' => 'Wonosobo', 'phone_number' => null],
            ['full_name' => 'AL FARI\'AH ALFA FARIDHOTUN NI\'MAH', 'nis' => 'C-415', 'nisn' => '0055396008', 'gender' => 'Perempuan', 'address' => 'SUKOHARJO', 'phone_number' => null],
            ['full_name' => 'Angga Febrian', 'nis' => 'C-416', 'nisn' => '0025668586', 'gender' => 'Laki-laki', 'address' => 'SURAKARTA', 'phone_number' => null],
            ['full_name' => 'APRILISTIA', 'nis' => 'C-417', 'nisn' => '0031950763', 'gender' => 'Perempuan', 'address' => 'WONOSOBO', 'phone_number' => null],
            ['full_name' => 'Arwin Syarif Hidayat', 'nis' => 'C-418', 'nisn' => '0057129901', 'gender' => 'Laki-laki', 'address' => 'Banyumas', 'phone_number' => null],
            ['full_name' => 'DIVA EKA ISMANINGSIH', 'nis' => 'C-419', 'nisn' => '0057556012', 'gender' => 'Perempuan', 'address' => 'BANYUMAS', 'phone_number' => null],
            ['full_name' => 'DWI MIYANTO', 'nis' => 'C-420', 'nisn' => '3858157044', 'gender' => 'Laki-laki', 'address' => 'SURAKARTA', 'phone_number' => null],
            ['full_name' => 'FEBRIANA PUTRI SETYAWATI', 'nis' => 'C-421', 'nisn' => '0074232868', 'gender' => 'Perempuan', 'address' => 'SURAKARTA', 'phone_number' => null],
            ['full_name' => 'HADINTA DHARMA', 'nis' => 'C-422', 'nisn' => '0064072288', 'gender' => 'Laki-laki', 'address' => 'SUKOHARJO', 'phone_number' => null],
            ['full_name' => 'Hilma Khoirotun Hisan', 'nis' => 'C-423', 'nisn' => '0056890988', 'gender' => 'Laki-laki', 'address' => 'Sukoharjo', 'phone_number' => null],
            ['full_name' => 'HUMAIRA ZULFA KHOODHI\'', 'nis' => 'C-424', 'nisn' => '0071884857', 'gender' => 'Perempuan', 'address' => 'SEMARANG', 'phone_number' => null],
            ['full_name' => 'JENI RAHMAWATI', 'nis' => 'C-425', 'nisn' => '0031076418', 'gender' => 'Perempuan', 'address' => 'WONOSOBO', 'phone_number' => null],
            ['full_name' => 'JESIKA APRILIANI', 'nis' => 'C-426', 'nisn' => '0071615966', 'gender' => 'Perempuan', 'address' => 'KAB.SEMARANG', 'phone_number' => null],
            ['full_name' => 'KHOLIFATUN NURAINI', 'nis' => 'C-427', 'nisn' => '3056236362', 'gender' => 'Perempuan', 'address' => 'BANJARNEGARA', 'phone_number' => null],
            ['full_name' => 'LATIFAH', 'nis' => 'C-428', 'nisn' => '0028825031', 'gender' => 'Perempuan', 'address' => 'WONOSOBO', 'phone_number' => null],
            ['full_name' => 'LUTHFI ASLAMA', 'nis' => 'C-429', 'nisn' => '0078103315', 'gender' => 'Laki-laki', 'address' => 'SURAKARTA', 'phone_number' => null],
            ['full_name' => 'LUTHFI MUFID', 'nis' => 'C-430', 'nisn' => '0057498693', 'gender' => 'Laki-laki', 'address' => 'PURBALINGGA', 'phone_number' => null],
            ['full_name' => 'LUTHFI SAFINATUN NAJWA', 'nis' => 'C-431', 'nisn' => '0059495817', 'gender' => 'Perempuan', 'address' => 'PURBALINGGA', 'phone_number' => null],
            ['full_name' => 'MAHDI SYAHPUTRI HAREFA', 'nis' => 'C-432', 'nisn' => '0038676335', 'gender' => 'Perempuan', 'address' => 'GUNUNG SITOLI', 'phone_number' => null],
            ['full_name' => 'MISNIAT', 'nis' => 'C-433', 'nisn' => '3831307578', 'gender' => 'Perempuan', 'address' => 'PACITAN', 'phone_number' => null],
            ['full_name' => 'MORENO BRYAN UMARDAN', 'nis' => 'C-434', 'nisn' => '0037554020', 'gender' => 'Laki-laki', 'address' => 'SEMARANG', 'phone_number' => null],
            ['full_name' => 'MUH SULISTYO SAPUTRO', 'nis' => 'C-435', 'nisn' => '0077089988', 'gender' => 'Laki-laki', 'address' => 'BOYOLALI', 'phone_number' => null],
            ['full_name' => 'Muhammad Abbas Khoirullah', 'nis' => 'C-436', 'nisn' => '2065248940', 'gender' => 'Laki-laki', 'address' => 'Surakarta', 'phone_number' => null],
            ['full_name' => 'MUHAMMAD ARNADA JULIANSYAH', 'nis' => 'C-437', 'nisn' => '0077330243', 'gender' => 'Laki-laki', 'address' => 'BREBES', 'phone_number' => null],
            ['full_name' => 'Muhammad Ilham Saputra', 'nis' => 'C-438', 'nisn' => '0036973749', 'gender' => 'Laki-laki', 'address' => 'SURAKARTA', 'phone_number' => null],
            ['full_name' => 'MUHAMMAD RIO TRI LESMANA', 'nis' => 'C-439', 'nisn' => '0036698887', 'gender' => 'Laki-laki', 'address' => 'SUKOHARJO', 'phone_number' => null],
            ['full_name' => 'NAADIYAH RIFA AGNIA', 'nis' => 'C-440', 'nisn' => '3069858916', 'gender' => 'Perempuan', 'address' => 'BANYUMAS', 'phone_number' => null],
            ['full_name' => 'NANDA PRASETYO', 'nis' => 'C-441', 'nisn' => '3990119777', 'gender' => 'Laki-laki', 'address' => 'SURAKARTA', 'phone_number' => null],
            ['full_name' => 'NUR AFIFAH', 'nis' => 'C-442', 'nisn' => '0031950553', 'gender' => 'Perempuan', 'address' => 'WONOSOBO', 'phone_number' => null],
            ['full_name' => 'NUR SYAFIRA ZAKKIYYAH', 'nis' => 'C-443', 'nisn' => '3053898914', 'gender' => 'Perempuan', 'address' => 'CILACAP', 'phone_number' => null],
            ['full_name' => 'PANGGIH NUGROHO', 'nis' => 'C-444', 'nisn' => '3848534229', 'gender' => 'Laki-laki', 'address' => 'SURAKARTA', 'phone_number' => null],
            ['full_name' => 'Rahmat Adi Wibowo', 'nis' => 'C-445', 'nisn' => '0062405688', 'gender' => 'Laki-laki', 'address' => 'Grobogan', 'phone_number' => null],
            ['full_name' => 'RIKI DZULKURNAEN', 'nis' => 'C-446', 'nisn' => '0032546314', 'gender' => 'Laki-laki', 'address' => 'WONOSOBO', 'phone_number' => null],
            ['full_name' => 'SARWOKO', 'nis' => 'C-447', 'nisn' => '3822221101', 'gender' => 'Laki-laki', 'address' => 'SURAKARTA', 'phone_number' => null],
            ['full_name' => 'Septian Wijanarko', 'nis' => 'C-448', 'nisn' => '0046256566', 'gender' => 'Laki-laki', 'address' => 'Surakarta', 'phone_number' => null],
            ['full_name' => 'SYAHLA ROSYIFAH', 'nis' => 'C-449', 'nisn' => '0055326143', 'gender' => 'Perempuan', 'address' => 'PURBALINGGA', 'phone_number' => null],
            ['full_name' => 'TOFIK Cahyo', 'nis' => 'C-450', 'nisn' => '0046336437', 'gender' => 'Laki-laki', 'address' => 'Karanganyar', 'phone_number' => null],
            ['full_name' => 'TRUBUS AMINUDIN', 'nis' => 'C-451', 'nisn' => '3723254171', 'gender' => 'Laki-laki', 'address' => 'BOYOLALI', 'phone_number' => null],
            ['full_name' => 'ULFI NUR AZIZAH', 'nis' => 'C-452', 'nisn' => '0042514550', 'gender' => 'Perempuan', 'address' => 'TEMANGGUNG', 'phone_number' => null],
            ['full_name' => 'VANESHA EFENDI', 'nis' => 'C-453', 'nisn' => '0037077899', 'gender' => 'Perempuan', 'address' => 'JAKARTA', 'phone_number' => null],
            ['full_name' => 'WAHONO WIDODO', 'nis' => 'C-454', 'nisn' => '3867145792', 'gender' => 'Laki-laki', 'address' => 'SURAKARTA', 'phone_number' => null],
            ['full_name' => 'WARDI PRASETYO', 'nis' => 'C-455', 'nisn' => '3868615632', 'gender' => 'Laki-laki', 'address' => 'SURAKARTA', 'phone_number' => null],
            ['full_name' => 'WIDODO', 'nis' => 'C-456', 'nisn' => '3868219298', 'gender' => 'Laki-laki', 'address' => 'SURAKARTA', 'phone_number' => null],
            ['full_name' => 'WINDA SAPUTRI', 'nis' => 'C-457', 'nisn' => '0061789991', 'gender' => 'Perempuan', 'address' => 'BREBES', 'phone_number' => null],
            ['full_name' => 'YAIR ZAKHARIA SETIAWAN', 'nis' => 'C-458', 'nisn' => '0046375416', 'gender' => 'Laki-laki', 'address' => 'SURAKARTA', 'phone_number' => null],
            ['full_name' => 'YULIANA DESMAWATI', 'nis' => 'C-459', 'nisn' => '3960089192', 'gender' => 'Perempuan', 'address' => 'SUKOHARJO', 'phone_number' => null],
            ['full_name' => 'Zahra Vallia Aryana Rivai', 'nis' => 'C-460', 'nisn' => '0061237253', 'gender' => 'Perempuan', 'address' => 'Wonogiri', 'phone_number' => null],
            ['full_name' => 'ZAKARIA NAUFAL RIZAL', 'nis' => 'C-461', 'nisn' => '0069809812', 'gender' => 'Laki-laki', 'address' => 'SUKOHARJO', 'phone_number' => null],
        ];

        DB::table('students')->insert($students);

        $this->command->info('20 Students seeded successfully!');
    }
}
